E0-I13
Sistem-Pack/practicum-android-diploma pull request #30
Opened 2024-03-31 18:23 UTC by Sistem-Pack

PR решает вопросы связанные с Issue 13
Добавлены следующие элементы:
1. BottomNavigationMenu
2. Корректировка тем и наследования в темах
3. Иконки для BottomNavigationMenu
4. Отдельные дневные/ночные ресурсы для BottomNavigationMenu
5. Добавлены строковые ресурсы для BottomnavigationMenu
6. Добавлен 1 элемент размера в 1dp в ресурсы размеров

2024-03-31 21:52 UTC, Eka666Sed commented
В app/src/main/res/layout/activity_root.xml есть атрибут android:background="@color/white" у Toolbar. Если его не убрать, то в темной теме экраны будут иметь белую полосу в Toolbar.
![photo_2024-03-31_23-50-22](https://github.com/Sistem-Pack/practicum-android-diploma/assets/130983590/b5b9eec3-daba-43ee-8ac6-713198a7543d)

2024-03-31 21:58 UTC, Eka666Sed commented
В app/src/main/res/layout/activity_root.xml      в <androidx.constraintlayout.widget.ConstraintLayout атрибут android:background="@color/white" не меняет цвета бэкграунда (цвет меняется темой как я поняла).

2024-03-31 22:12 UTC, Eka666Sed commented
Возможно при мердже съедет моя верстка на экране команды из-за ToolBar. Может без ToolBar в activity_root.xml обойдемся?  Сделаем на конкретных экранах?

2024-03-31 22:15 UTC, MountSwan requested changes

2024-03-31 22:15 UTC, MountSwan commented on app/src/main/res/layout/activity_root.xml
> +        android:background="@color/gray"
У разделяющей полосы цвет должен быть не gray, а light_gray.

2024-03-31 22:15 UTC, MountSwan commented on app/src/main/res/layout/activity_root.xml
> +        android:background="@color/white"
Когда устанавливаем цвет фона "белый", в темной теме он тоже будет белым, а должен быть черным. В темах уже установлены цвета для фона (белая - для светлой темы, черная - для темной). Они действуют по умолчанию, поэтому цвет для фона имеет смысл устанавливать только тогда, когда он должен отличаться от этих цветов. Так что нужно убрать строку android:background="@color/white" точно из Тулбара, потому что из-за этого в темной теме вылезает белая полоса. Ну и 7 строка тоже без надобности, хоть она визуально и не вредит.

2024-04-01 04:39 UTC, Sistem-Pack commented on app/src/main/res/layout/activity_root.xml
> +        android:background="@color/gray"
Поправил

2024-04-01 04:39 UTC, Sistem-Pack commented on app/src/main/res/layout/activity_root.xml
> +        android:background="@color/white"
Убрал Toolbar

2024-04-01 04:47 UTC, Babaylov7 approved these changes

2024-04-01 04:50 UTC, Babaylov7 approved these changes

2024-04-01 06:34 UTC, DaniilKosmachev approved these changes

2024-04-01 12:12 UTC, merged